simulated_motors:
  - "/hrim_actuation_servomotor_000000000001/trajectory_axis2"
  - "/hrim_actuation_servomotor_000000000001/trajectory_axis1"
  - "/hrim_actuation_servomotor_000000000002/trajectory_axis1"
  - "/hrim_actuation_servomotor_000000000002/trajectory_axis2"
  - "/hrim_actuation_servomotor_000000000003/trajectory_axis1"
  - "/hrim_actuation_servomotor_000000000003/trajectory_axis2"

real_motors:
  - "/hrim_actuation_servomotor_70B3D521A084/trajectory_axis2"
  - "/hrim_actuation_servomotor_70B3D521A084/trajectory_axis1"
  - "/hrim_actuation_servomotor_70B3D521A0C0/trajectory_axis1"
  - "/hrim_actuation_servomotor_70B3D521A0C0/trajectory_axis2"
  - "/hrim_actuation_servomotor_70B3D521A092/trajectory_axis1"
  - "/hrim_actuation_servomotor_70B3D521A092/trajectory_axis2"
