simulated_motors:
  - "/hrim_actuator_rotaryservo_000000000001/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000001/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000002/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000002/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000003/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000003/trajectory_axis2"

real_motors:
  - "/hrim_actuator_rotaryservo_70B3D521A042/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A042/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A08A/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A08A/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A0A4/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A0A4/trajectory_axis2"

motors:
  - "motor1"
  - "motor2"
  - "motor3"
  - "motor4"
  - "motor5"
  - "motor6"
