simulated_motors:
  - "/hrim_actuator_rotaryservo_000000000001/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000001/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000002/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000002/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000003/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000003/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000005/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000005/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000006/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000006/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_000000000007/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_000000000007/trajectory_axis2"

real_motors:
  - "/hrim_actuator_rotaryservo_70B3D521A042/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A042/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A08A/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A08A/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A0A4/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A0A4/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A084/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A084/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A0C0/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A0C0/trajectory_axis2"
  - "/hrim_actuator_rotaryservo_70B3D521A092/trajectory_axis1"
  - "/hrim_actuator_rotaryservo_70B3D521A092/trajectory_axis2"

motors:
  - "motor1"
  - "motor2"
  - "motor3"
  - "motor4"
  - "motor5"
  - "motor6"
  - "mara2_motor1"
  - "mara2_motor2"
  - "mara2_motor3"
  - "mara2_motor4"
  - "mara2_motor5"
  - "mara2_motor6"
